### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by mgaitan** [Dancer3809/PgDiffPy#3]
I want to fork this repo to improve the project (for instance, improve the package layout and make it installable) and use it my own project, but I need to be sure it's a under BSD/MIT or other of open source bussiness friendly license. 

Please, choose one and add it. 

thanks in advance

**Comment by Gesha3809** [comment]
Feel free to fork and improve the project.

**Comment by mgaitan** [comment]
great, thanks
